### ISSUE TITLE
Todo list: 新的录像标识系统

### ISSUE THREAD

**Issue by putianyi889** [eee555/saolei_website#85]
1. 用户上传录像
   - [ ] 对标识进行审查并存储审查结果
   - [ ] if 审查不通过则丢弃录像，返回审查错误
   - [ ] if 未过机审，记作FROZEN
   - [ ] elseif 在用户的标识列表中则记作OFFICIAL，刷新用户纪录
   - [ ] else记作DESIGNATOR
2. 用户添加标识
   - [ ] 查询标识审查结果
   - [ ] if 未查到结果或审查不通过，说明没有该标识的录像，返回错误
   - [ ] if 该标识已被其他用户占用，返回标识冲突
   - [ ] if 该标识已被用户添加过，返回http错误（前端本应阻止）
   - [ ] 查找所有该用户该标识录像
   - [ ] if 查不到则添加失败
   - [ ] else 将所有DESIGNATOR状态改成OFFICIAL
3. 用户删除标识
   - [ ] if 该标识不存在或不属于该用户，返回http错误
   - [ ] 将该标识所属用户清空
   - [ ] 查找所有该用户该标识录像，将所有OFFICIAL改成DESIGNATOR，改完以后再刷新用户纪录
4. 管理员冻结录像
   - [ ] 将状态改为FROZEN
5. 管理员审核录像
   - [ ] if 在用户的标识列表中则记作OFFICIAL，刷新用户纪录
   - [ ] else记作DESIGNATOR

- [ ] 标识改用identifier

**Comment by putianyi889** [comment]
管理员冻结与审核录像另起issue
